services:
  app:
    build: .
    ports:
      - '3545:3000'
    volumes:
      - ./data:/app/data:rw,z
    env_file:
      - .env
    security_opt:
      - seccomp:unconfined
      - label:disable
    restart: unless-stopped
